export const business = {
  brand: 'Toquetea',
  productName: {
    es: 'créditos para creadores con IA',
    en: 'AI builder credits',
  },
  whatsappNumber: '573103434694',
  whatsappDisplay: '+57 310 343 4694',
  email: 'toquetea@proton.me',
  year: '2026',
};

export const packages = [
  {
    id: 'starter',
    name: { es: '100 créditos', en: '100 credits' },
    credits: '100',
    price: '$10 USD',
    highlighted: false,
    features: {
      es: ['Entrega rápida', 'Soporte directo', 'Ideal para probar Lovable'],
      en: ['Fast delivery', 'Direct support', 'Ideal for trying Lovable'],
    },
  },
  {
    id: 'builder',
    name: { es: '300 créditos', en: '300 credits' },
    credits: '300',
    price: '$30 USD',
    highlighted: true,
    features: {
      es: ['Mejor equilibrio precio/volumen', 'Entrega prioritaria', 'Para creadores frecuentes'],
      en: ['Best price-to-volume balance', 'Priority delivery', 'For frequent builders'],
    },
  },
  {
    id: 'pro',
    name: { es: '500 créditos', en: '500 credits' },
    credits: '500',
    price: '$50 USD',
    highlighted: false,
    features: {
      es: ['Más créditos por pedido', 'Soporte dedicado', 'Para equipos y proyectos activos'],
      en: ['More credits per order', 'Dedicated support', 'For teams and active projects'],
    },
  },
];

// Cambia available a false para ocultar temporalmente una cuenta no disponible.
export const services = [
  {
    id: 'chatgpt-plus',
    available: true,
    name: 'ChatGPT Plus',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: '$12 USD', en: '$12 USD' },
    features: {
      es: ['Cuenta privada Plus', 'Acceso durante 1 mes', 'Ideal para estudio, trabajo y contenido'],
      en: ['Private Plus account', '1 month access', 'Ideal for study, work, and content'],
    },
  },
  {
    id: 'reddit',
    available: true,
    name: 'Reddit',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Uso para comunidades y contenido', 'Soporte por WhatsApp'],
      en: ['Private account', 'For communities and content', 'WhatsApp support'],
    },
  },
  {
    id: 'cursor-ai',
    available: true,
    name: 'Cursor AI',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$149 USD', en: '$149 USD' },
    features: {
      es: ['Cuenta privada anual', 'Asistente IA para programar', 'Ideal para desarrolladores y equipos'],
      en: ['Annual private account', 'AI coding assistant', 'Ideal for developers and teams'],
    },
  },
  {
    id: 'gamma-ai',
    available: true,
    name: 'Gamma AI',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Presentaciones con IA', 'Ideal para propuestas y clases'],
      en: ['Private account', 'AI presentations', 'Ideal for proposals and classes'],
    },
  },
  {
    id: 'leonardo-ai',
    available: true,
    name: 'Leonardo AI',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Generación de imágenes con IA', 'Ideal para marcas y creativos'],
      en: ['Private account', 'AI image generation', 'Ideal for brands and creatives'],
    },
  },
  {
    id: 'n8n',
    available: true,
    name: 'n8n Starter Pack',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$79 USD', en: '$79 USD' },
    features: {
      es: ['Starter Pack anual', 'Automatizaciones e integraciones', 'Ideal para flujos de trabajo y negocios'],
      en: ['Annual Starter Pack', 'Automations and integrations', 'Ideal for workflows and business'],
    },
  },
  {
    id: 'canva-pro',
    available: true,
    name: 'Canva Pro',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$12 USD', en: '$12 USD' },
    features: {
      es: ['Activación en tu cuenta', 'Plantillas y recursos Pro', 'Ideal para diseño y contenido'],
      en: ['Activated on your account', 'Pro templates and assets', 'Ideal for design and content'],
    },
  },
  {
    id: 'canva-business',
    available: true,
    name: 'Canva Business',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$19 USD', en: '$19 USD' },
    features: {
      es: ['Cuenta Business anual', 'Funciones para equipos', 'Ideal para marcas y agencias'],
      en: ['Annual Business account', 'Team features', 'Ideal for brands and agencies'],
    },
  },
  {
    id: 'coursera-plus',
    available: true,
    name: 'Coursera Plus',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$25 USD', en: '$25 USD' },
    features: {
      es: ['Acceso anual Plus', 'Cursos y certificados elegibles', 'Ideal para formación profesional'],
      en: ['Annual Plus access', 'Eligible courses and certificates', 'Ideal for professional learning'],
    },
  },
];

// Cambia available a false para ocultar temporalmente una API no disponible.
export const apis = [
  {
    id: 'openai-api',
    available: true,
    featured: true,
    category: 'LLMs / Chat',
    name: 'OpenAI API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['GPT-5, GPT-5-mini, GPT-5-nano y GPT-5.2', 'Texto, razonamiento, Whisper y TTS', 'Ideal para apps, agentes y automatizaciones'],
      en: ['GPT-5, GPT-5-mini, GPT-5-nano, and GPT-5.2', 'Text, reasoning, Whisper, and TTS', 'Ideal for apps, agents, and automations'],
    },
  },
  {
    id: 'claude-api',
    available: true,
    featured: true,
    category: 'LLMs / Chat',
    name: 'Claude API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['Modelos Claude de Anthropic', 'Excelente para análisis, escritura y código', 'Soporte inicial de configuración'],
      en: ['Anthropic Claude models', 'Great for analysis, writing, and code', 'Initial setup support'],
    },
  },
  {
    id: 'gemini-api',
    available: true,
    featured: true,
    category: 'LLMs / Chat',
    name: 'Gemini API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Gemini 2.5 Pro/Flash y Gemini 3', 'Texto, multimodal e imagen Nano Banana 2', 'Ideal para productos con Google AI'],
      en: ['Gemini 2.5 Pro/Flash and Gemini 3', 'Text, multimodal, and Nano Banana 2 image', 'Ideal for Google AI products'],
    },
  },
  {
    id: 'deepseek-api',
    available: true,
    featured: true,
    category: 'LLMs / Chat',
    name: 'DeepSeek API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['DeepSeek V3 y R1 para razonamiento', 'Eficiente para texto, código y agentes IA', 'Muy solicitado por su costo/rendimiento'],
      en: ['DeepSeek V3 and R1 for reasoning', 'Efficient for text, code, and AI agents', 'Popular for cost/performance'],
    },
  },
  {
    id: 'openrouter-api',
    available: true,
    featured: true,
    category: 'LLMs / Chat',
    name: 'OpenRouter API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$30 USD', en: '$30 USD' },
    price: { es: '$15 USD', en: '$15 USD' },
    discount: '50% OFF',
    features: {
      es: ['Acceso a 200+ modelos', 'Ideal para probar varios proveedores', 'Una sola integración para muchos modelos'],
      en: ['Access to 200+ models', 'Ideal for testing several providers', 'One integration for many models'],
    },
  },
  {
    id: 'elevenlabs-api',
    available: true,
    featured: true,
    category: 'Audio',
    name: 'ElevenLabs API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['TTS, voice cloning y diálogo', 'Voces expresivas v3', 'Ideal para agentes de voz y contenido'],
      en: ['TTS, voice cloning, and dialogue', 'Expressive v3 voices', 'Ideal for voice agents and content'],
    },
  },
  {
    id: 'lovable-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Lovable API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Acceso para flujos Lovable', 'Ideal para builders y automatizaciones', 'Soporte por WhatsApp'],
      en: ['Access for Lovable workflows', 'Ideal for builders and automations', 'WhatsApp support'],
    },
  },
  {
    id: 'groq-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Groq API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Llama y Mixtral ultra-rápidos', 'Inferencia de baja latencia', 'Ideal para chatbots veloces'],
      en: ['Ultra-fast Llama and Mixtral', 'Low-latency inference', 'Ideal for fast chatbots'],
    },
  },
  {
    id: 'cerebras-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Cerebras API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Llama y Qwen-3', 'Inferencia ultra-fast', 'Ideal para respuestas en tiempo real'],
      en: ['Llama and Qwen-3', 'Ultra-fast inference', 'Ideal for real-time responses'],
    },
  },
  {
    id: 'grok-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Grok API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['Grok 4 de xAI', 'Capacidades multimodales', 'Ideal para productos experimentales'],
      en: ['xAI Grok 4', 'Multimodal capabilities', 'Ideal for experimental products'],
    },
  },
  {
    id: 'moonshot-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Moonshot API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Kimi K2.5', 'Contexto amplio y buen razonamiento', 'Ideal para asistentes y análisis'],
      en: ['Kimi K2.5', 'Long context and good reasoning', 'Ideal for assistants and analysis'],
    },
  },
  {
    id: 'perplexity-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Perplexity API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Sonar con web search', 'Respuestas con información actual', 'Ideal para investigación y agentes'],
      en: ['Sonar with web search', 'Answers with current information', 'Ideal for research and agents'],
    },
  },
  {
    id: 'qwen-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Qwen API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$18 USD', en: '$18 USD' },
    price: { es: '$9 USD', en: '$9 USD' },
    discount: '50% OFF',
    features: {
      es: ['Qwen Max y Omni', 'Audio, video y generación multimodal', 'Ideal para productos avanzados'],
      en: ['Qwen Max and Omni', 'Audio, video, and multimodal generation', 'Ideal for advanced products'],
    },
  },
  {
    id: 'cohere-api',
    available: true,
    category: 'LLMs / Chat',
    name: 'Cohere API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Command R+', 'RAG y búsqueda empresarial', 'Ideal para bases de conocimiento'],
      en: ['Command R+', 'RAG and enterprise search', 'Ideal for knowledge bases'],
    },
  },
  {
    id: 'stability-api',
    available: true,
    category: 'Imagen / Video',
    name: 'Stability API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['SDXL y SD3', 'Imagen e image-to-video', 'Ideal para generación visual'],
      en: ['SDXL and SD3', 'Image and image-to-video', 'Ideal for visual generation'],
    },
  },
  {
    id: 'freepik-api',
    available: true,
    category: 'Imagen / Video',
    name: 'Freepik API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Mystic, Flux, Seedream y Kling video', 'Imagen y video generativo', 'Ideal para contenido creativo'],
      en: ['Mystic, Flux, Seedream, and Kling video', 'Generative image and video', 'Ideal for creative content'],
    },
  },
  {
    id: 'ideogram-api',
    available: true,
    category: 'Imagen',
    name: 'Ideogram API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Texto dentro de imágenes', 'Ideal para ads, posters y logos', 'Resultados creativos rápidos'],
      en: ['Text inside images', 'Ideal for ads, posters, and logos', 'Fast creative outputs'],
    },
  },
  {
    id: 'heygen-api',
    available: true,
    category: 'Video',
    name: 'HeyGen API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['Avatares y video con voz', 'Ideal para ventas y capacitación', 'Soporte inicial de configuración'],
      en: ['Avatars and voice video', 'Ideal for sales and training', 'Initial setup support'],
    },
  },
  {
    id: 'deepgram-api',
    available: true,
    category: 'Audio',
    name: 'Deepgram API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['STT Nova-2 y TTS Aura', 'Ideal para llamadas y transcripción', 'Baja latencia para voz'],
      en: ['Nova-2 STT and Aura TTS', 'Ideal for calls and transcription', 'Low-latency voice workflows'],
    },
  },
  {
    id: 'brave-api',
    available: true,
    category: 'Búsqueda / Scraping',
    name: 'Brave Search API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$10 USD', en: '$10 USD' },
    price: { es: '$6 USD', en: '$6 USD' },
    discount: '40% OFF',
    features: {
      es: ['Web search', 'Ideal para agentes con búsqueda', 'Resultados actuales'],
      en: ['Web search', 'Ideal for search agents', 'Current results'],
    },
  },
  {
    id: 'firecrawl-api',
    available: true,
    category: 'Búsqueda / Scraping',
    name: 'Firecrawl API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Web scraping estructurado', 'Ideal para datasets y agentes', 'Convierte webs en datos útiles'],
      en: ['Structured web scraping', 'Ideal for datasets and agents', 'Turns websites into useful data'],
    },
  },
  {
    id: 'apify-api',
    available: true,
    category: 'Búsqueda / Scraping',
    name: 'Apify API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['100+ actores listos', 'YouTube, WhatsApp, Skool y más', 'Ideal para extracción de datos'],
      en: ['100+ ready actors', 'YouTube, WhatsApp, Skool, and more', 'Ideal for data extraction'],
    },
  },
  {
    id: 'google-api',
    available: true,
    category: 'Búsqueda / Scraping',
    name: 'Google APIs',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$20 USD', en: '$20 USD' },
    price: { es: '$10 USD', en: '$10 USD' },
    discount: '50% OFF',
    features: {
      es: ['Maps, Places y Geocode', 'Ideal para negocios locales', 'Datos geográficos y ubicaciones'],
      en: ['Maps, Places, and Geocode', 'Ideal for local businesses', 'Geographic and location data'],
    },
  },
  {
    id: 'youtube-api',
    available: true,
    category: 'Búsqueda / Scraping',
    name: 'YouTube Data API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$15 USD', en: '$15 USD' },
    price: { es: '$8 USD', en: '$8 USD' },
    discount: '47% OFF',
    features: {
      es: ['Transcripts y datos de canales', '4 niveles de fallback', 'Ideal para análisis de contenido'],
      en: ['Transcripts and channel data', '4 fallback levels', 'Ideal for content analysis'],
    },
  },
  {
    id: 'twocaptcha-api',
    available: true,
    category: 'Utilidades',
    name: '2Captcha API',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$10 USD', en: '$10 USD' },
    price: { es: '$6 USD', en: '$6 USD' },
    discount: '40% OFF',
    features: {
      es: ['Resolución de captchas', 'Ideal para automatizaciones', 'Soporte inicial de integración'],
      en: ['Captcha solving', 'Ideal for automations', 'Initial integration support'],
    },
  },
  {
    id: 'opencode-api',
    available: true,
    category: 'Utilidades',
    name: 'OpenCode Proxy',
    usage: { es: 'Acceso API', en: 'API access' },
    originalPrice: { es: '$25 USD', en: '$25 USD' },
    price: { es: '$12 USD', en: '$12 USD' },
    discount: '52% OFF',
    features: {
      es: ['Proxy multimodal con failover', 'Ideal para productos robustos', 'Ruteo entre modelos'],
      en: ['Multimodal proxy with failover', 'Ideal for robust products', 'Routing across models'],
    },
  },
];

export const copy = {
  es: {
    nav: ['Cómo funciona', 'Créditos Lovable', 'APIs', 'Cuentas IA', 'Por qué nosotros', 'Preguntas', 'Contacto'],
    navAria: 'Navegación principal',
    homeAria: 'Inicio de Toquetea',
    heroEyebrow: 'Proveedor confiable de créditos digitales',
    heroTitle: 'Compra créditos y cuentas privadas para construir más rápido.',
    heroText:
      'Créditos digitales, cuentas privadas y accesos a herramientas de IA con entrega rápida, soporte directo y una compra sin fricción.',
    primaryCta: 'Ver paquetes',
    whatsappCta: 'Comprar por WhatsApp',
    orderMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes compartir más información?',
    infoMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes compartir más información?',
    highlightsAria: 'Beneficios principales',
    highlights: ['Entrega instantánea', 'Pago seguro', 'Servicio global', 'Soporte humano'],
    heroVisualAria: 'Visual de entrega de créditos',
    panelLabel: 'Orden activa',
    panelValue: '+300 créditos',
    panelText: 'En cola para entrega instantánea',
    floatingCardTitle: 'Toquetea',
    floatingCardText: 'Créditos y cuentas privadas',
    miniTop: 'Pago verificado',
    miniBottom: 'Entrega confirmada',
    statsAria: 'Estadísticas',
    providersAria: 'Proveedores y plataformas',
    providersEyebrow: 'Catálogo',
    providersTitle: 'Las herramientas que ya conoces',
    providersText:
      'Logos solo para identificación. No implican afiliación oficial; somos un servicio independiente de accesos y créditos.',
    trustTitle: 'Confianza global para entregas digitales',
    stats: ['2,500+ clientes atendidos', '50,000+ créditos entregados', '99.8% satisfacción', 'Soporte 24/7'],
    processEyebrow: 'Proceso',
    stepsTitle: 'Compra en 3 pasos simples',
    stepsText: 'Elige un paquete de créditos Lovable, confirma por WhatsApp y recibe la entrega en minutos.',
    steps: [
      ['Elige tu paquete', 'Selecciona el volumen de créditos Lovable que encaje con tu flujo en el builder.'],
      ['Confirma por WhatsApp', 'El mensaje se prepara automáticamente para agilizar la compra.'],
      ['Recibe tus créditos Lovable', 'Coordinamos la entrega tras confirmar el pago y el acceso a tu workspace.'],
    ],
    servicesEyebrow: 'Cuentas IA',
    servicesTitle: 'Cuentas privadas y herramientas digitales',
    servicesText: 'Accesos de IA, diseño, automatización y formación. Puedes activar o desactivar cada cuenta desde el archivo de datos.',
    serviceCta: 'Comprar',
    serviceMessage: 'Hola, estoy interesado en el servicio',
    pricingEyebrow: 'Lovable',
    packagesTitle: 'Paquetes de créditos Lovable',
    packagesText:
      'Recarga créditos para tu workspace en Lovable (builder con IA). Planes listos para creadores solos, freelancers y equipos que despliegan a producción sin fricción.',
    featuredBadge: 'Mejor valor',
    creditsLabel: 'créditos Lovable',
    customTitle: 'Personalizado',
    unlimited: 'Sin límite',
    customPrice: 'A medida',
    customText: 'Créditos Lovable a medida para compras grandes, recargas recurrentes o equipos.',
    customFeatures: ['Cantidad personalizada', 'Descuentos por volumen', 'Soporte prioritario', 'Recargas recurrentes'],
    buyMessage: 'Hola, quiero comprar créditos Lovable — plan',
    customMessage: 'Hola, quiero un paquete personalizado de créditos Lovable. ¿Me puedes compartir más información?',
    apisEyebrow: 'APIs',
    apisTitle: 'Accesos API',
    apisText: 'Mostramos las APIs más solicitadas con precio regular y descuento Toquetea. Despliega el catálogo completo para ver más proveedores.',
    apiCta: 'Comprar',
    apiMessage: 'Hola, estoy interesado en la API',
    apiRegularPrice: 'Precio regular',
    apiToqueteaPrice: 'Con Toquetea',
    apiDiscountPrefix: 'HASTA',
    apiShowMore: 'Ver más APIs',
    apiShowLess: 'Ver menos',
    trustEyebrow: 'Confianza',
    whyTitle: 'Por qué elegirnos',
    whyText: 'Una experiencia de compra directa, segura y optimizada para equipos que no quieren perder tiempo.',
    reasons: [
      ['Seguro', 'Operación verificada y comunicación directa antes de cada entrega.'],
      ['Rápido', 'Atención por WhatsApp con respuestas preparadas para reducir espera.'],
      ['Global', 'Servicio para clientes en América, Europa, MENA y Asia.'],
      ['Flexible', 'Paquetes fijos o compras personalizadas para necesidades especiales.'],
      ['Transparente', 'Precios claros, sin cargos ocultos ni pasos innecesarios.'],
      ['Acompañado', 'Soporte humano para resolver dudas antes y después de la compra.'],
    ],
    testimonialsAria: 'Testimonios',
    testimonialsEyebrow: 'Testimonios',
    testimonialsTitleStart: 'Amado por creadores',
    testimonialsTitleAccent: 'vibe coders',
    testimonialsTitleEnd: 'en todo el mundo',
    testimonialsSubtitle: 'Reseñas reales de creadores y equipos que confían en Toquetea.',
    testimonials: [
      {
        initials: 'AR',
        name: 'Alex R.',
        role: 'Desarrollador indie, USA',
        quote: 'Compré el paquete de 300 créditos y los recibí en menos de 2 minutos. Una experiencia increíblemente fluida. Volveré por más.',
      },
      {
        initials: 'SM',
        name: 'Sophie M.',
        role: 'Profesional independiente, UK',
        quote: 'Confiable, rápido y con gran valor. Toquetea es mi opción cuando necesito recargar sin complicaciones.',
      },
      {
        initials: 'TA',
        name: 'Tariq A.',
        role: 'Dueño de agencia, UAE',
        quote: 'Compramos packs de 500 créditos Lovable para el equipo. El soporte por WhatsApp es muy rápido. Muy recomendado.',
      },
      {
        initials: 'MR',
        name: 'María R.',
        role: 'Creadora de contenido, Colombia',
        quote: 'Compré Canva Pro y la activación fue sencilla. Me explicaron todo por WhatsApp y pude empezar a diseñar el mismo día.',
      },
      {
        initials: 'JD',
        name: 'Juan D.',
        role: 'Desarrollador, México',
        quote: 'Cursor AI me llegó rápido y el precio fue muy bueno para todo el año. Lo uso a diario para programar más rápido.',
      },
      {
        initials: 'LC',
        name: 'Laura C.',
        role: 'Estudiante, Chile',
        quote: 'ChatGPT Plus funcionó perfecto. La atención fue clara, rápida y sin vueltas. Muy confiable.',
      },
      {
        initials: 'PG',
        name: 'Pablo G.',
        role: 'Automatizador, Argentina',
        quote: 'El pack de n8n me ayudó a montar flujos para clientes. Buen soporte y respuesta rápida cuando tuve dudas.',
      },
      {
        initials: 'NV',
        name: 'Natalia V.',
        role: 'Diseñadora, Perú',
        quote: 'Leonardo AI fue justo lo que necesitaba para generar imágenes para mis campañas. La compra fue muy fluida.',
      },
      {
        initials: 'FS',
        name: 'Felipe S.',
        role: 'Agencia digital, España',
        quote: 'Pedimos varios accesos para el equipo y todo llegó coordinado. Buen servicio para compras por volumen.',
      },
      {
        initials: 'AM',
        name: 'Ana M.',
        role: 'Consultora, Ecuador',
        quote: 'Coursera Plus quedó activo rápido y me sirvió para seguir varias certificaciones sin pagar el precio completo.',
      },
      {
        initials: 'RS',
        name: 'Rafael S.',
        role: 'Builder no-code, Brasil',
        quote: 'Los créditos de Lovable llegaron sin problema. Me gustó que el mensaje de compra ya saliera listo en WhatsApp.',
      },
    ],
    faqTitle: 'Preguntas frecuentes',
    faqEyebrow: 'Preguntas',
    faqs: [
      ['¿Qué son los créditos?', 'Son unidades digitales usadas dentro de plataformas de construcción con IA para generar, editar o iterar proyectos.'],
      ['¿Cuánto tarda la entrega?', 'Normalmente se coordina en minutos tras confirmar el pago y la información necesaria.'],
      ['¿Qué métodos de pago aceptan?', 'Aceptamos tarjeta, Dropi, Binance y PayPal.'],
      ['¿Puedo pedir un paquete personalizado?', 'Sí, se pueden preparar cotizaciones para equipos, agencias o recargas recurrentes.'],
    ],
    contactTitle: 'Hablemos',
    contactEyebrow: 'Contacto',
    contactText: '¿Tienes preguntas o necesitas un pedido a medida? Escríbenos y te respondemos rápido.',
    contactMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes ayudar?',
    disclaimer: 'Servicio independiente de recarga y gestion de creditos digitales.',
    buy: 'Comprar',
    quote: 'Cotizar paquete personalizado',
    footerRights: 'Todos los derechos reservados.',
    language: 'English',
  },
  en: {
    nav: ['How it works', 'Lovable credits', 'APIs', 'AI accounts', 'Why us', 'FAQ', 'Contact'],
    navAria: 'Main navigation',
    homeAria: 'Toquetea home',
    heroEyebrow: 'Trusted digital credits provider',
    heroTitle: 'Buy credits and private accounts to build faster.',
    heroText:
      'Digital credits, private accounts, and AI tool access with fast delivery, direct support, and a frictionless purchase flow.',
    primaryCta: 'See packages',
    whatsappCta: 'Buy on WhatsApp',
    orderMessage: 'Hi, I am interested in buying credits or private accounts. Can you share more information?',
    infoMessage: 'Hi, I am interested in buying credits or private accounts. Can you share more information?',
    highlightsAria: 'Main benefits',
    highlights: ['Instant delivery', 'Secure checkout', 'Worldwide service', 'Human support'],
    heroVisualAria: 'Credit delivery visual',
    panelLabel: 'Live order',
    panelValue: '+300 credits',
    panelText: 'Queued for instant delivery',
    floatingCardTitle: 'Toquetea',
    floatingCardText: 'Credits and private accounts',
    miniTop: 'Verified payment',
    miniBottom: 'Delivery confirmed',
    statsAria: 'Statistics',
    providersAria: 'Providers and platforms',
    providersEyebrow: 'Catalog',
    providersTitle: 'Tools you already know',
    providersText:
      'Logos are for identification only. They do not imply official affiliation; we are an independent access and credits service.',
    trustTitle: 'Trusted worldwide for digital delivery',
    stats: ['2,500+ customers served', '50,000+ credits delivered', '99.8% satisfaction', '24/7 support'],
    processEyebrow: 'Process',
    stepsTitle: 'Buy in 3 simple steps',
    stepsText: 'Choose a Lovable credit pack, confirm on WhatsApp, and get delivery in minutes.',
    steps: [
      ['Choose your package', 'Pick the Lovable credit volume that fits your builder workflow.'],
      ['Confirm on WhatsApp', 'The order message is prepared automatically to speed up checkout.'],
      ['Receive your Lovable credits', 'Delivery is coordinated after payment and workspace access are confirmed.'],
    ],
    servicesEyebrow: 'AI accounts',
    servicesTitle: 'Private accounts and digital tools',
    servicesText: 'AI, design, automation, and learning access. Enable or disable each account from the data file.',
    serviceCta: 'Buy',
    serviceMessage: 'Hi, I am interested in the service',
    pricingEyebrow: 'Lovable',
    packagesTitle: 'Lovable credit packs',
    packagesText:
      'Top up credits for your Lovable AI builder workspace. Ready-made packs for solo makers, freelancers, and teams shipping to production without friction.',
    featuredBadge: 'Best value',
    creditsLabel: 'Lovable credits',
    customTitle: 'Custom',
    unlimited: 'Unlimited',
    customPrice: 'Custom',
    customText: 'Tailored Lovable credits for larger orders, recurring top-ups, or teams.',
    customFeatures: ['Any credit amount', 'Volume discounts', 'Concierge support', 'Recurring top-ups'],
    buyMessage: 'Hi, I want to buy Lovable credits — plan',
    customMessage: 'Hi, I want a custom Lovable credit pack. Can you share more information?',
    apisEyebrow: 'APIs',
    apisTitle: 'API access',
    apisText: 'We show the most requested APIs with regular price and Toquetea discount. Expand the full catalog to see more providers.',
    apiCta: 'Buy',
    apiMessage: 'Hi, I am interested in the API',
    apiRegularPrice: 'Regular price',
    apiToqueteaPrice: 'With Toquetea',
    apiDiscountPrefix: 'UP TO',
    apiShowMore: 'See more APIs',
    apiShowLess: 'See less',
    trustEyebrow: 'Trust',
    whyTitle: 'Why choose us',
    whyText: 'A direct, secure, and optimized purchase experience for teams that do not want delays.',
    reasons: [
      ['Secure', 'Verified operation and direct communication before every delivery.'],
      ['Fast', 'WhatsApp support with prepared flows to reduce waiting time.'],
      ['Global', 'Service for customers across America, Europe, MENA, and Asia.'],
      ['Flexible', 'Fixed packages or custom purchases for special requirements.'],
      ['Transparent', 'Clear pricing with no hidden charges or unnecessary steps.'],
      ['Supported', 'Human support before and after every order.'],
    ],
    testimonialsAria: 'Testimonials',
    testimonialsEyebrow: 'Testimonials',
    testimonialsTitleStart: 'Loved by',
    testimonialsTitleAccent: 'vibe coders',
    testimonialsTitleEnd: 'worldwide',
    testimonialsSubtitle: 'Real reviews from builders and agencies who trust Toquetea.',
    testimonials: [
      {
        initials: 'AR',
        name: 'Alex R.',
        role: 'Indie Developer, USA',
        quote: 'Bought the 300 Lovable credits pack and got delivery in under 2 minutes. Incredibly smooth experience. Will be coming back for more!',
      },
      {
        initials: 'SM',
        name: 'Sophie M.',
        role: 'Freelancer, UK',
        quote: 'Trusted, fast, and great value. Toquetea is my go-to whenever I need to top up. No fuss, just credits.',
      },
      {
        initials: 'TA',
        name: 'Tariq A.',
        role: 'Agency Owner, UAE',
        quote: 'We buy 500-credit Lovable packs regularly for our team builds. WhatsApp support is super responsive. Highly recommended.',
      },
      {
        initials: 'MR',
        name: 'Maria R.',
        role: 'Content Creator, Colombia',
        quote: 'I bought Canva Pro and activation was simple. They explained everything on WhatsApp and I started designing the same day.',
      },
      {
        initials: 'JD',
        name: 'Juan D.',
        role: 'Developer, Mexico',
        quote: 'Cursor AI arrived quickly and the yearly price was great. I use it every day to code faster.',
      },
      {
        initials: 'LC',
        name: 'Laura C.',
        role: 'Student, Chile',
        quote: 'ChatGPT Plus worked perfectly. The support was clear, fast, and straightforward. Very trustworthy.',
      },
      {
        initials: 'PG',
        name: 'Pablo G.',
        role: 'Automation Specialist, Argentina',
        quote: 'The n8n pack helped me build workflows for clients. Good support and quick replies when I had questions.',
      },
      {
        initials: 'NV',
        name: 'Natalia V.',
        role: 'Designer, Peru',
        quote: 'Leonardo AI was exactly what I needed to create images for my campaigns. The purchase was very smooth.',
      },
      {
        initials: 'FS',
        name: 'Felipe S.',
        role: 'Digital Agency, Spain',
        quote: 'We ordered several accesses for the team and everything was coordinated properly. Great service for volume orders.',
      },
      {
        initials: 'AM',
        name: 'Ana M.',
        role: 'Consultant, Ecuador',
        quote: 'Coursera Plus was activated quickly and helped me follow several certifications without paying full price.',
      },
      {
        initials: 'RS',
        name: 'Rafael S.',
        role: 'No-code Builder, Brazil',
        quote: 'The Lovable credits arrived without issues. I liked that the WhatsApp order message was already prepared.',
      },
    ],
    faqTitle: 'Frequently asked questions',
    faqEyebrow: 'FAQ',
    faqs: [
      ['What are credits?', 'They are digital units used inside AI building platforms to generate, edit, or iterate projects.'],
      ['How long does delivery take?', 'It is usually coordinated within minutes after payment and required account details are confirmed.'],
      ['What payment methods do you accept?', 'We accept card payments, Dropi, Binance, and PayPal.'],
      ['Can I request a custom package?', 'Yes, quotes can be prepared for teams, agencies, or recurring top-ups.'],
    ],
    contactTitle: 'Get in touch',
    contactEyebrow: 'Contact',
    contactText: 'Have questions or need a custom order? Message us and we will reply quickly.',
    contactMessage: 'Hi, I am interested in buying credits or private accounts. Can you help me?',
    disclaimer: 'Independent digital credits top-up and management service.',
    buy: 'Buy',
    quote: 'Request custom quote',
    footerRights: 'All rights reserved.',
    language: 'Español',
  },
};
