export const business = {
  brand: 'Toquetea',
  productName: {
    es: 'créditos para creadores con IA',
    en: 'AI builder credits',
  },
  whatsappNumber: '573103434694',
  whatsappDisplay: '+57 310 343 4694',
  email: 'toquetea@proton.me',
  year: '2026',
};

export const packages = [
  {
    id: 'starter',
    name: { es: 'Starter', en: 'Starter' },
    credits: '100',
    price: '$4 USD',
    highlighted: false,
    features: {
      es: ['Entrega rápida', 'Soporte directo', 'Ideal para pruebas'],
      en: ['Fast delivery', 'Direct support', 'Ideal for testing'],
    },
  },
  {
    id: 'builder',
    name: { es: 'Builder', en: 'Builder' },
    credits: '300',
    price: '$8 USD',
    highlighted: true,
    features: {
      es: ['Entrega prioritaria', 'Mejor valor inicial', 'Para creadores frecuentes'],
      en: ['Priority delivery', 'Best starter value', 'For frequent builders'],
    },
  },
  {
    id: 'pro',
    name: { es: 'Pro', en: 'Pro' },
    credits: '600',
    price: '$15 USD',
    highlighted: false,
    features: {
      es: ['Ahorro por crédito', 'Soporte dedicado', 'Para proyectos activos'],
      en: ['Lower cost per credit', 'Dedicated support', 'For active projects'],
    },
  },
  {
    id: 'agency',
    name: { es: 'Agencia', en: 'Agency' },
    credits: '1,000',
    price: '$28 USD',
    highlighted: false,
    features: {
      es: ['Compra por volumen', 'Atención prioritaria', 'Facturación a medida'],
      en: ['Bulk purchase', 'Priority attention', 'Custom invoicing'],
    },
  },
];

// Cambia available a false para ocultar temporalmente una cuenta no disponible.
export const services = [
  {
    id: 'chatgpt-plus',
    available: true,
    name: 'ChatGPT Plus',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: '$12 USD', en: '$12 USD' },
    features: {
      es: ['Cuenta privada Plus', 'Acceso durante 1 mes', 'Ideal para estudio, trabajo y contenido'],
      en: ['Private Plus account', '1 month access', 'Ideal for study, work, and content'],
    },
  },
  {
    id: 'reddit',
    available: true,
    name: 'Reddit',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Uso para comunidades y contenido', 'Soporte por WhatsApp'],
      en: ['Private account', 'For communities and content', 'WhatsApp support'],
    },
  },
  {
    id: 'cursor-ai',
    available: true,
    name: 'Cursor AI',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$149 USD', en: '$149 USD' },
    features: {
      es: ['Cuenta privada anual', 'Asistente IA para programar', 'Ideal para desarrolladores y equipos'],
      en: ['Annual private account', 'AI coding assistant', 'Ideal for developers and teams'],
    },
  },
  {
    id: 'gamma-ai',
    available: true,
    name: 'Gamma AI',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Presentaciones con IA', 'Ideal para propuestas y clases'],
      en: ['Private account', 'AI presentations', 'Ideal for proposals and classes'],
    },
  },
  {
    id: 'leonardo-ai',
    available: true,
    name: 'Leonardo AI',
    duration: { es: '1 mes', en: '1 month' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Cuenta privada', 'Generación de imágenes con IA', 'Ideal para marcas y creativos'],
      en: ['Private account', 'AI image generation', 'Ideal for brands and creatives'],
    },
  },
  {
    id: 'n8n',
    available: true,
    name: 'n8n Starter Pack',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$79 USD', en: '$79 USD' },
    features: {
      es: ['Starter Pack anual', 'Automatizaciones e integraciones', 'Ideal para flujos de trabajo y negocios'],
      en: ['Annual Starter Pack', 'Automations and integrations', 'Ideal for workflows and business'],
    },
  },
  {
    id: 'canva-pro',
    available: true,
    name: 'Canva Pro',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$12 USD', en: '$12 USD' },
    features: {
      es: ['Activación en tu cuenta', 'Plantillas y recursos Pro', 'Ideal para diseño y contenido'],
      en: ['Activated on your account', 'Pro templates and assets', 'Ideal for design and content'],
    },
  },
  {
    id: 'canva-business',
    available: true,
    name: 'Canva Business',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$19 USD', en: '$19 USD' },
    features: {
      es: ['Cuenta Business anual', 'Funciones para equipos', 'Ideal para marcas y agencias'],
      en: ['Annual Business account', 'Team features', 'Ideal for brands and agencies'],
    },
  },
  {
    id: 'coursera-plus',
    available: true,
    name: 'Coursera Plus',
    duration: { es: '1 año', en: '1 year' },
    price: { es: '$25 USD', en: '$25 USD' },
    features: {
      es: ['Acceso anual Plus', 'Cursos y certificados elegibles', 'Ideal para formación profesional'],
      en: ['Annual Plus access', 'Eligible courses and certificates', 'Ideal for professional learning'],
    },
  },
];

// Cambia available a false para ocultar temporalmente una API no disponible.
export const apis = [
  {
    id: 'openai-api',
    available: true,
    name: 'OpenAI API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Acceso configurado', 'Soporte inicial', 'Ideal para automatizaciones'],
      en: ['Configured access', 'Initial support', 'Ideal for automations'],
    },
  },
  {
    id: 'claude-api',
    available: true,
    name: 'Claude API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Acceso configurado', 'Soporte inicial', 'Para flujos con IA'],
      en: ['Configured access', 'Initial support', 'For AI workflows'],
    },
  },
  {
    id: 'gemini-api',
    available: true,
    name: 'Gemini API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Acceso configurado', 'Soporte inicial', 'Uso flexible'],
      en: ['Configured access', 'Initial support', 'Flexible usage'],
    },
  },
  {
    id: 'openrouter-api',
    available: true,
    name: 'OpenRouter API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Acceso a múltiples modelos', 'Ideal para comparar proveedores', 'Soporte inicial de configuración'],
      en: ['Access to multiple models', 'Ideal for comparing providers', 'Initial setup support'],
    },
  },
  {
    id: 'lovable-api',
    available: true,
    name: 'Lovable API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Acceso para flujos Lovable', 'Ideal para builders y automatizaciones', 'Soporte por WhatsApp'],
      en: ['Access for Lovable workflows', 'Ideal for builders and automations', 'WhatsApp support'],
    },
  },
  {
    id: 'deepseek-api',
    available: true,
    name: 'DeepSeek API',
    usage: { es: 'Acceso API', en: 'API access' },
    price: { es: 'Consultar', en: 'Ask price' },
    features: {
      es: ['Modelos eficientes para texto y código', 'Ideal para apps y agentes IA', 'Soporte inicial de configuración'],
      en: ['Efficient models for text and code', 'Ideal for apps and AI agents', 'Initial setup support'],
    },
  },
];

export const copy = {
  es: {
    nav: ['Cómo funciona', 'Paquetes', 'APIs', 'Cuentas IA', 'Por qué nosotros', 'Preguntas', 'Contacto'],
    navAria: 'Navegación principal',
    homeAria: 'Inicio de Toquetea',
    heroEyebrow: 'Proveedor confiable de créditos digitales',
    heroTitle: 'Compra créditos y cuentas privadas para construir más rápido.',
    heroText:
      'Créditos digitales, cuentas privadas y accesos a herramientas de IA con entrega rápida, soporte directo y una compra sin fricción.',
    primaryCta: 'Ver paquetes',
    whatsappCta: 'Comprar por WhatsApp',
    orderMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes compartir más información?',
    infoMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes compartir más información?',
    highlightsAria: 'Beneficios principales',
    highlights: ['Entrega instantánea', 'Pago seguro', 'Servicio global', 'Soporte humano'],
    heroVisualAria: 'Visual de entrega de créditos',
    panelLabel: 'Orden activa',
    panelValue: '+300 créditos',
    panelText: 'En cola para entrega instantánea',
    floatingCardTitle: 'Toquetea',
    floatingCardText: 'Créditos y cuentas privadas',
    miniTop: 'Pago verificado',
    miniBottom: 'Entrega confirmada',
    statsAria: 'Estadísticas',
    trustTitle: 'Confianza global para entregas digitales',
    stats: ['2,500+ clientes atendidos', '50,000+ créditos entregados', '99.8% satisfacción', 'Soporte 24/7'],
    processEyebrow: 'Proceso',
    stepsTitle: 'Compra en 3 pasos simples',
    stepsText: 'Elige un paquete, confirma por WhatsApp y recibe instrucciones de entrega en minutos.',
    steps: [
      ['Elige tu paquete', 'Selecciona la cantidad de créditos que se ajusta a tu flujo de trabajo.'],
      ['Confirma por WhatsApp', 'El mensaje se prepara automáticamente para agilizar la compra.'],
      ['Recibe tus créditos', 'Coordinamos la entrega tras confirmar el pago y los datos de cuenta.'],
    ],
    servicesEyebrow: 'Cuentas IA',
    servicesTitle: 'Cuentas privadas y herramientas digitales',
    servicesText: 'Accesos de IA, diseño, automatización y formación. Puedes activar o desactivar cada cuenta desde el archivo de datos.',
    serviceCta: 'Comprar',
    serviceMessage: 'Hola, estoy interesado en el servicio',
    pricingEyebrow: 'Precios',
    packagesTitle: 'Paquetes de créditos',
    packagesText: 'Opciones listas para creadores individuales, profesionales independientes y equipos.',
    featuredBadge: 'Mejor valor',
    creditsLabel: 'créditos',
    customTitle: 'Personalizado',
    unlimited: 'Sin límite',
    customPrice: 'A medida',
    customText: 'Créditos a medida para compras grandes, recargas recurrentes o equipos.',
    customFeatures: ['Cantidad personalizada', 'Descuentos por volumen', 'Soporte prioritario', 'Recargas recurrentes'],
    buyMessage: 'Hola, estoy interesado en el plan',
    customMessage: 'Hola, estoy interesado en un plan personalizado. ¿Me puedes compartir más información?',
    apisEyebrow: 'APIs',
    apisTitle: 'Accesos API',
    apisText: 'Opciones de API listas para configurar. Los precios y características se pueden ajustar desde el archivo de datos.',
    apiCta: 'Comprar',
    apiMessage: 'Hola, estoy interesado en la API',
    trustEyebrow: 'Confianza',
    whyTitle: 'Por qué elegirnos',
    whyText: 'Una experiencia de compra directa, segura y optimizada para equipos que no quieren perder tiempo.',
    reasons: [
      ['Seguro', 'Operación verificada y comunicación directa antes de cada entrega.'],
      ['Rápido', 'Atención por WhatsApp con respuestas preparadas para reducir espera.'],
      ['Global', 'Servicio para clientes en América, Europa, MENA y Asia.'],
      ['Flexible', 'Paquetes fijos o compras personalizadas para necesidades especiales.'],
      ['Transparente', 'Precios claros, sin cargos ocultos ni pasos innecesarios.'],
      ['Acompañado', 'Soporte humano para resolver dudas antes y después de la compra.'],
    ],
    testimonialsAria: 'Testimonios',
    testimonialsEyebrow: 'Testimonios',
    testimonialsTitleStart: 'Amado por creadores',
    testimonialsTitleAccent: 'vibe coders',
    testimonialsTitleEnd: 'en todo el mundo',
    testimonialsSubtitle: 'Reseñas reales de creadores y equipos que confían en Toquetea.',
    testimonials: [
      {
        initials: 'AR',
        name: 'Alex R.',
        role: 'Desarrollador indie, USA',
        quote: 'Compré el paquete Builder y recibí mis créditos en menos de 2 minutos. Una experiencia increíblemente fluida. Volveré por más.',
      },
      {
        initials: 'SM',
        name: 'Sophie M.',
        role: 'Profesional independiente, UK',
        quote: 'Confiable, rápido y con gran valor. Toquetea es mi opción cuando necesito recargar sin complicaciones.',
      },
      {
        initials: 'TA',
        name: 'Tariq A.',
        role: 'Dueño de agencia, UAE',
        quote: 'Compramos paquetes Agency regularmente para nuestro equipo. El soporte por WhatsApp es muy rápido. Muy recomendado.',
      },
    ],
    faqTitle: 'Preguntas frecuentes',
    faqEyebrow: 'Preguntas',
    faqs: [
      ['¿Qué son los créditos?', 'Son unidades digitales usadas dentro de plataformas de construcción con IA para generar, editar o iterar proyectos.'],
      ['¿Cuánto tarda la entrega?', 'Normalmente se coordina en minutos tras confirmar el pago y la información necesaria.'],
      ['¿Qué métodos de pago aceptan?', 'Aceptamos tarjeta, Dropi, Binance y PayPal.'],
      ['¿Puedo pedir un paquete personalizado?', 'Sí, se pueden preparar cotizaciones para equipos, agencias o recargas recurrentes.'],
    ],
    contactTitle: 'Hablemos',
    contactEyebrow: 'Contacto',
    contactText: '¿Tienes preguntas o necesitas un pedido a medida? Escríbenos y te respondemos rápido.',
    contactMessage: 'Hola, estoy interesado en comprar créditos o cuentas privadas. ¿Me puedes ayudar?',
    disclaimer: 'Servicio independiente de recarga y gestion de creditos digitales.',
    buy: 'Comprar',
    quote: 'Cotizar paquete personalizado',
    footerRights: 'Todos los derechos reservados.',
    language: 'English',
  },
  en: {
    nav: ['How it works', 'Packages', 'APIs', 'AI accounts', 'Why us', 'FAQ', 'Contact'],
    navAria: 'Main navigation',
    homeAria: 'Toquetea home',
    heroEyebrow: 'Trusted digital credits provider',
    heroTitle: 'Buy credits and private accounts to build faster.',
    heroText:
      'Digital credits, private accounts, and AI tool access with fast delivery, direct support, and a frictionless purchase flow.',
    primaryCta: 'See packages',
    whatsappCta: 'Buy on WhatsApp',
    orderMessage: 'Hi, I am interested in buying credits or private accounts. Can you share more information?',
    infoMessage: 'Hi, I am interested in buying credits or private accounts. Can you share more information?',
    highlightsAria: 'Main benefits',
    highlights: ['Instant delivery', 'Secure checkout', 'Worldwide service', 'Human support'],
    heroVisualAria: 'Credit delivery visual',
    panelLabel: 'Live order',
    panelValue: '+300 credits',
    panelText: 'Queued for instant delivery',
    floatingCardTitle: 'Toquetea',
    floatingCardText: 'Credits and private accounts',
    miniTop: 'Verified payment',
    miniBottom: 'Delivery confirmed',
    statsAria: 'Statistics',
    trustTitle: 'Trusted worldwide for digital delivery',
    stats: ['2,500+ customers served', '50,000+ credits delivered', '99.8% satisfaction', '24/7 support'],
    processEyebrow: 'Process',
    stepsTitle: 'Buy in 3 simple steps',
    stepsText: 'Choose a package, confirm on WhatsApp, and receive delivery instructions in minutes.',
    steps: [
      ['Choose your package', 'Pick the credit amount that matches your workflow.'],
      ['Confirm on WhatsApp', 'The order message is prepared automatically to speed up checkout.'],
      ['Receive your credits', 'Delivery is coordinated after payment and account details are confirmed.'],
    ],
    servicesEyebrow: 'AI accounts',
    servicesTitle: 'Private accounts and digital tools',
    servicesText: 'AI, design, automation, and learning access. Enable or disable each account from the data file.',
    serviceCta: 'Buy',
    serviceMessage: 'Hi, I am interested in the service',
    packagesTitle: 'Credit packages',
    packagesText: 'Ready-made options for solo creators, freelancers, and teams.',
    pricingEyebrow: 'Pricing',
    featuredBadge: 'Best value',
    creditsLabel: 'credits',
    customTitle: 'Custom',
    unlimited: 'Unlimited',
    customPrice: 'Custom',
    customText: 'Tailored credits for larger orders, recurring top-ups, or teams.',
    customFeatures: ['Any credit amount', 'Volume discounts', 'Concierge support', 'Recurring top-ups'],
    buyMessage: 'Hi, I am interested in the plan',
    customMessage: 'Hi, I am interested in a custom plan. Can you share more information?',
    apisEyebrow: 'APIs',
    apisTitle: 'API access',
    apisText: 'API options ready to configure. Prices and features can be adjusted from the data file.',
    apiCta: 'Buy',
    apiMessage: 'Hi, I am interested in the API',
    trustEyebrow: 'Trust',
    whyTitle: 'Why choose us',
    whyText: 'A direct, secure, and optimized purchase experience for teams that do not want delays.',
    reasons: [
      ['Secure', 'Verified operation and direct communication before every delivery.'],
      ['Fast', 'WhatsApp support with prepared flows to reduce waiting time.'],
      ['Global', 'Service for customers across America, Europe, MENA, and Asia.'],
      ['Flexible', 'Fixed packages or custom purchases for special requirements.'],
      ['Transparent', 'Clear pricing with no hidden charges or unnecessary steps.'],
      ['Supported', 'Human support before and after every order.'],
    ],
    testimonialsAria: 'Testimonials',
    testimonialsEyebrow: 'Testimonials',
    testimonialsTitleStart: 'Loved by',
    testimonialsTitleAccent: 'vibe coders',
    testimonialsTitleEnd: 'worldwide',
    testimonialsSubtitle: 'Real reviews from builders and agencies who trust Toquetea.',
    testimonials: [
      {
        initials: 'AR',
        name: 'Alex R.',
        role: 'Indie Developer, USA',
        quote: 'Bought the Builder pack and got my credits in under 2 minutes. Incredibly smooth experience. Will be coming back for more!',
      },
      {
        initials: 'SM',
        name: 'Sophie M.',
        role: 'Freelancer, UK',
        quote: 'Trusted, fast, and great value. Toquetea is my go-to whenever I need to top up. No fuss, just credits.',
      },
      {
        initials: 'TA',
        name: 'Tariq A.',
        role: 'Agency Owner, UAE',
        quote: 'We buy Agency packs regularly for our team builds. WhatsApp support is super responsive. Highly recommended.',
      },
    ],
    faqTitle: 'Frequently asked questions',
    faqEyebrow: 'FAQ',
    faqs: [
      ['What are credits?', 'They are digital units used inside AI building platforms to generate, edit, or iterate projects.'],
      ['How long does delivery take?', 'It is usually coordinated within minutes after payment and required account details are confirmed.'],
      ['What payment methods do you accept?', 'We accept card payments, Dropi, Binance, and PayPal.'],
      ['Can I request a custom package?', 'Yes, quotes can be prepared for teams, agencies, or recurring top-ups.'],
    ],
    contactTitle: 'Get in touch',
    contactEyebrow: 'Contact',
    contactText: 'Have questions or need a custom order? Message us and we will reply quickly.',
    contactMessage: 'Hi, I am interested in buying credits or private accounts. Can you help me?',
    disclaimer: 'Independent digital credits top-up and management service.',
    buy: 'Buy',
    quote: 'Request custom quote',
    footerRights: 'All rights reserved.',
    language: 'Español',
  },
};
